-- run_test.py: invoking following command in '/home/dorson/Documents/github/Doe/src/doe_control':
 - /opt/ros/jazzy/bin/ament_flake8 --xunit-file /home/dorson/Documents/github/Doe/src/doe_control/build/doe_control/test_results/doe_control/flake8.xunit.xml


2 files checked
No problems found

Checked files:

* ./install/_local_setup_util_ps1.py
* ./install/_local_setup_util_sh.py


-- run_test.py: return code 0
-- run_test.py: verify result file '/home/dorson/Documents/github/Doe/src/doe_control/build/doe_control/test_results/doe_control/flake8.xunit.xml'
